name: Deploy Test
  
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: codebuild-github-protection-testing-${{ github.run_id }}-${{ github.run_attempt }}
    environment: test
    steps:
      - run: echo "Deployed!"
